name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    outputs:
      perl-versions: ${{ steps.perl-versions.outputs.perl-versions }}
    steps:
      - id: perl-versions
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: 5.14
          with-devel: false

  linux:
    needs: perl-versions
    runs-on: ubuntu-latest
    name: "Linux / Perl ${{ matrix.perl-version }}"

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTOMATED_TESTING: 1

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v6
      - name: perl -V
        run: perl -V
      - name: Install Dist::Zilla and dependencies
        run: |
          cpm install -g --show-build-log-on-failure Dist::Zilla
          cpm install -g --show-build-log-on-failure $(dzil authordeps --missing | tr '\n' ' ')
          cpm install -g --show-build-log-on-failure $(dzil listdeps --missing | tr '\n' ' ')
      - name: Build
        run: dzil build --in build
      - name: Run Tests
        run: |
          cd build
          prove -lr t/
