name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    outputs:
      perl-versions: ${{ steps.perl-versions.outputs.perl-versions }}
    steps:
      - id: perl-versions
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: 5.14
          with-devel: false

  linux:
    needs: perl-versions
    runs-on: ubuntu-latest
    name: "Linux / Perl ${{ matrix.perl-version }}"

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTOMATED_TESTING: 1

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v6
      - run: perl -V
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: ".github/cpanfile.ci"
      - name: Build and Test
        run: |
          if command -v dzil &> /dev/null; then
            dzil build --in build
            cd build
          fi
          prove -lr t/
